name: Statistics-CI

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - battery-statistics/stats_script.py

permissions:
  contents: write

jobs:
  ci:
     name: CI
     runs-on: ubuntu-latest
     
     steps:
       - name: Checkout
         uses: actions/checkout@v2
        #  with:
        #    fetch-depth: 0 

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
         with:
           platforms: arm

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

      #  - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
       - name: Build and Push
         uses: docker/build-push-action@v5
         with:
           context: ./battery-statistics
           platforms: linux/arm/v7
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/battery-statistics:latest